default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: Pk@7470588990
  host: localhost

development:
  <<: *default
  database: itassetmgt

test:
  <<: *default
  database: itassetmgt

production:
  <<: *default
  database: itassetmgt
