default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: itassetmgt
  username: postgres
  password: sqlpass
  host: 103.228.83.115

  production:
  <<: *default
  database: itassetmgt
  username: postgres
  password: sqlpass
  host: 103.228.83.115