
default: &default
  adapter: postgresql
  encoding: unicode
  database: dcalqvapf4vgdi
  pool: 5
  username: postgres
  password: Pk@7470588990
  host: localhost

development:
  <<: *default
  database: dcalqvapf4vgdi

test:
  <<: *default
  database: dcalqvapf4vgdi

production:
  <<: *default
  database: dcalqvapf4vgdi
  username: postgres
  password: <%= ENV["ITASSETMGT_DATABASE_PASSWORD"] %>
