default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5

development:
  <<: *default
  username: postgres
  password: sqlpass
  host: 103.228.83.115

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
