
default: &default
  adapter: postgresql
  encoding: unicode
  database: itassetmgt
  pool: 5
  username: postgres
  password: Pk@7470588990
  host: localhost
  port: 5432

development:
  <<: *default
  database: itassetmgt

test:
  <<: *default
  database: itassetmgt

production:
  <<: *default
  database: itassetmgt
  username: postgres
  password: <%= ENV["ITASSETMGT_DATABASE_PASSWORD"] %>
